In [4]:
import numpy as np

## numpy array

In [2]:
benimListem = [20,30,40]

In [4]:
type(benimListem)

list

In [5]:
np.array(benimListem)

array([20, 30, 40])

In [6]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [9]:
matrixListesi[1][0]

20

In [10]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspace

In [25]:
np.linspace(1,2,4)

array([1.        , 1.33333333, 1.66666667, 2.        ])

## eye

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random

In [26]:
np.random.randn(4)

array([-0.40039081,  0.41302396,  1.15956136,  0.47763318])

In [36]:
np.random.randint(1,6)

5

In [38]:
np.random.randint(1,300,5)

array([144, 131, 281, 136, 176])

In [39]:
benimNumpyDizim = np.arange(30)

In [46]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [47]:
benimRandomDizim = np.random.randint(0,100,30)

In [48]:
benimRandomDizim

array([ 0, 41, 31, 59, 77, 18, 13, 82, 57, 53, 21, 88, 40, 42, 64, 73, 58,
       74, 17, 77, 54,  6, 58, 63, 56, 74, 33, 83, 96, 47])

## numpy dizi methodları

In [50]:
benimNumpyDizim.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [52]:
benimNumpyDizim.max()

29

In [53]:
benimRandomDizim.max()

96

In [56]:
benimRandomDizim.min()

0

In [58]:
benimRandomDizim.argmax()

28

In [60]:
benimRandomDizim.argmin()

0

In [64]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [66]:
reshapeDizim.shape

(5, 6)