In [24]:
import numpy as np

In [25]:
ND = np.array([1,2,3,4,5])
ND

array([1, 2, 3, 4, 5])

In [26]:
PL = [1,2,3,4,5]

In [27]:
PL

[1, 2, 3, 4, 5]

In [28]:
ND = np.array([[1,2,3,4,5],[1,2,3,4,5]])
ND

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [29]:
ND.shape

(2, 5)

In [30]:
ND.ndim

2

In [31]:
ND.dtype

dtype('int32')

In [32]:
type(ND)

numpy.ndarray

In [33]:
ND.size

10

In [34]:
ND3 = np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])

In [35]:
ND3

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [36]:
ND3.ndim

3

In [37]:
ND3.size

20

In [38]:
ND3.shape

(2, 2, 5)

In [39]:
ND0 = np.array(4)

In [40]:
ND0

array(4)

In [41]:
type(ND0)

numpy.ndarray

In [42]:
ND0.ndim

0

In [45]:
NDX = np.array([4])

In [46]:
NDX

array([4])

In [47]:
NDX.ndim

1