In [89]:
import pandas as pd
import numpy as np

In [90]:
pd.Series([10,-5,1.1,77.7])

0    10.0
1    -5.0
2     1.1
3    77.7
dtype: float64

In [91]:
pd.Series([10,-5,1.1,77.7], index=["Chandler","Bing","Bender","Rodrigez"])

Chandler    10.0
Bing        -5.0
Bender       1.1
Rodrigez    77.7
dtype: float64

In [92]:
data = {"İsim": ["Ahnet","Ezgi","Mehmet","Sevda"], #Not a Number
       "Boy": [180,170,150,np.nan], 
       "AyakkabıNumarası": [42,np.nan,39,36],
       "Kilo": [80,50,70,45]
       }

In [93]:
print(data)

{'İsim': ['Ahnet', 'Ezgi', 'Mehmet', 'Sevda'], 'Boy': [180, 170, 150, nan], 'AyakkabıNumarası': [42, nan, 39, 36], 'Kilo': [80, 50, 70, 45]}


In [94]:
from pprint import pprint
pprint(data)

{'AyakkabıNumarası': [42, nan, 39, 36],
 'Boy': [180, 170, 150, nan],
 'Kilo': [80, 50, 70, 45],
 'İsim': ['Ahnet', 'Ezgi', 'Mehmet', 'Sevda']}


In [95]:
randNumbers = np.random.random((7,4))

In [96]:
randNumbers

array([[0.87771953, 0.57755246, 0.75823626, 0.84348594],
       [0.76763167, 0.20691368, 0.29856958, 0.09823466],
       [0.15035265, 0.0859903 , 0.7258977 , 0.07740614],
       [0.95208492, 0.30904244, 0.178235  , 0.93708228],
       [0.02739245, 0.55590255, 0.22004797, 0.03581485],
       [0.99472083, 0.35991506, 0.76251411, 0.37227574],
       [0.62546428, 0.86337327, 0.27071266, 0.94008197]])

In [97]:
df = pd.DataFrame(randNumbers)
df

0         1         2         3
0  0.877720  0.577552  0.758236  0.843486
1  0.767632  0.206914  0.298570  0.098235
2  0.150353  0.085990  0.725898  0.077406
3  0.952085  0.309042  0.178235  0.937082
4  0.027392  0.555903  0.220048  0.035815
5  0.994721  0.359915  0.762514  0.372276
6  0.625464  0.863373  0.270713  0.940082

In [98]:
df = pd.DataFrame(randNumbers, columns = ["00.00","06.00","12.00","18.00"])

In [99]:
df

00.00     06.00     12.00     18.00
0  0.877720  0.577552  0.758236  0.843486
1  0.767632  0.206914  0.298570  0.098235
2  0.150353  0.085990  0.725898  0.077406
3  0.952085  0.309042  0.178235  0.937082
4  0.027392  0.555903  0.220048  0.035815
5  0.994721  0.359915  0.762514  0.372276
6  0.625464  0.863373  0.270713  0.940082

In [100]:
dates = pd.date_range("2021-03-09", periods=7)

In [101]:
dates

DatetimeIndex(['2021-03-09', '2021-03-10', '2021-03-11', '2021-03-12',
               '2021-03-13', '2021-03-14', '2021-03-15'],
              dtype='datetime64[ns]', freq='D')

In [102]:
df = pd.DataFrame(randNumbers,
                 index=dates,
                 columns=["00.00","06.00","12.00","18.00"])

In [103]:
df

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-13  0.027392  0.555903  0.220048  0.035815
2021-03-14  0.994721  0.359915  0.762514  0.372276
2021-03-15  0.625464  0.863373  0.270713  0.940082

In [104]:
df.dtypes

00.00    float64
06.00    float64
12.00    float64
18.00    float64
dtype: object

In [105]:
df2 = pd.DataFrame({"A": 1.0,
                   "B": pd.Timestamp("20210309"),
                   "C": pd.Series(1,index=list(range(4)),dtype="float32"),
                   "D": np.array([3]*4,dtype="int32"),
                   "E": pd.Categorical(["test","train","validation","train"]),
                   "F": "foo",
                   }
                  )

In [106]:
df2

A          B    C  D           E    F
0  1.0 2021-03-09  1.0  3        test  foo
1  1.0 2021-03-09  1.0  3       train  foo
2  1.0 2021-03-09  1.0  3  validation  foo
3  1.0 2021-03-09  1.0  3       train  foo

In [107]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [108]:
df

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-13  0.027392  0.555903  0.220048  0.035815
2021-03-14  0.994721  0.359915  0.762514  0.372276
2021-03-15  0.625464  0.863373  0.270713  0.940082

In [109]:
df.head()

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-13  0.027392  0.555903  0.220048  0.035815

In [110]:
df.head(2)

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  0.767632  0.206914  0.298570  0.098235

In [111]:
df.tail()

00.00     06.00     12.00     18.00
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-13  0.027392  0.555903  0.220048  0.035815
2021-03-14  0.994721  0.359915  0.762514  0.372276
2021-03-15  0.625464  0.863373  0.270713  0.940082

In [112]:
df.tail(2)

00.00     06.00     12.00     18.00
2021-03-14  0.994721  0.359915  0.762514  0.372276
2021-03-15  0.625464  0.863373  0.270713  0.940082

In [113]:
df.index

DatetimeIndex(['2021-03-09', '2021-03-10', '2021-03-11', '2021-03-12',
               '2021-03-13', '2021-03-14', '2021-03-15'],
              dtype='datetime64[ns]', freq='D')

In [114]:
df.columns.unique()

Index(['00.00', '06.00', '12.00', '18.00'], dtype='object')

In [115]:
df.to_numpy()

array([[0.87771953, 0.57755246, 0.75823626, 0.84348594],
       [0.76763167, 0.20691368, 0.29856958, 0.09823466],
       [0.15035265, 0.0859903 , 0.7258977 , 0.07740614],
       [0.95208492, 0.30904244, 0.178235  , 0.93708228],
       [0.02739245, 0.55590255, 0.22004797, 0.03581485],
       [0.99472083, 0.35991506, 0.76251411, 0.37227574],
       [0.62546428, 0.86337327, 0.27071266, 0.94008197]])

In [116]:
df.describe()

00.00     06.00     12.00     18.00
count  7.000000  7.000000  7.000000  7.000000
mean   0.627909  0.422670  0.459173  0.472055
std    0.389499  0.262270  0.273866  0.422100
min    0.027392  0.085990  0.178235  0.035815
25%    0.387908  0.257978  0.245380  0.087820
50%    0.767632  0.359915  0.298570  0.372276
75%    0.914902  0.566728  0.742067  0.890284
max    0.994721  0.863373  0.762514  0.940082

In [117]:
arr = np.array([1,2,3,4,5,6]).reshape(2,3)

In [118]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [120]:
arr.T.T

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
df.T

2021-03-09  2021-03-10  2021-03-11  2021-03-12  2021-03-13  2021-03-14  \
00.00    0.877720    0.767632    0.150353    0.952085    0.027392    0.994721   
06.00    0.577552    0.206914    0.085990    0.309042    0.555903    0.359915   
12.00    0.758236    0.298570    0.725898    0.178235    0.220048    0.762514   
18.00    0.843486    0.098235    0.077406    0.937082    0.035815    0.372276   

       2021-03-15  
00.00    0.625464  
06.00    0.863373  
12.00    0.270713  
18.00    0.940082

In [122]:
df

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-13  0.027392  0.555903  0.220048  0.035815
2021-03-14  0.994721  0.359915  0.762514  0.372276
2021-03-15  0.625464  0.863373  0.270713  0.940082

In [123]:
df.sort_index(axis=0)

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-13  0.027392  0.555903  0.220048  0.035815
2021-03-14  0.994721  0.359915  0.762514  0.372276
2021-03-15  0.625464  0.863373  0.270713  0.940082

In [124]:
df.sort_index(axis=0, ascending=False)

00.00     06.00     12.00     18.00
2021-03-15  0.625464  0.863373  0.270713  0.940082
2021-03-14  0.994721  0.359915  0.762514  0.372276
2021-03-13  0.027392  0.555903  0.220048  0.035815
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-09  0.877720  0.577552  0.758236  0.843486

In [125]:
df.sort_index(axis=1, ascending=False)

18.00     12.00     06.00     00.00
2021-03-09  0.843486  0.758236  0.577552  0.877720
2021-03-10  0.098235  0.298570  0.206914  0.767632
2021-03-11  0.077406  0.725898  0.085990  0.150353
2021-03-12  0.937082  0.178235  0.309042  0.952085
2021-03-13  0.035815  0.220048  0.555903  0.027392
2021-03-14  0.372276  0.762514  0.359915  0.994721
2021-03-15  0.940082  0.270713  0.863373  0.625464

In [126]:
df.sort_values(by="06.00")

00.00     06.00     12.00     18.00
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-14  0.994721  0.359915  0.762514  0.372276
2021-03-13  0.027392  0.555903  0.220048  0.035815
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-15  0.625464  0.863373  0.270713  0.940082

In [127]:
df["06.00"]

2021-03-09    0.577552
2021-03-10    0.206914
2021-03-11    0.085990
2021-03-12    0.309042
2021-03-13    0.555903
2021-03-14    0.359915
2021-03-15    0.863373
Freq: D, Name: 06.00, dtype: float64

In [128]:
df[0:3]

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-11  0.150353  0.085990  0.725898  0.077406

In [129]:
df.head()

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-13  0.027392  0.555903  0.220048  0.035815

In [130]:
idx = df.index[0]

In [131]:
idx

Timestamp('2021-03-09 00:00:00', freq='D')

In [132]:
df.loc[idx]

00.00    0.877720
06.00    0.577552
12.00    0.758236
18.00    0.843486
Name: 2021-03-09 00:00:00, dtype: float64

In [133]:
df.loc["2021-03-12": "2021-03-14", ["00.00","18.00"]]

00.00     18.00
2021-03-12  0.952085  0.937082
2021-03-13  0.027392  0.035815
2021-03-14  0.994721  0.372276

In [134]:
df.loc["2021-03-12", "00.00"]

0.9520849220961833

In [135]:
import time

In [136]:
start = time.time()
print("Değer:", df.loc["2021-03-14", "00.00"])
print(time.time()-start)

Değer: 0.994720826768822
0.000997304916381836


In [137]:
start = time.time()
print("Değer:", df.at["2021-03-14", "00.00"])
print(time.time()-start)

Değer: 0.994720826768822
0.000993490219116211


In [138]:
df

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-13  0.027392  0.555903  0.220048  0.035815
2021-03-14  0.994721  0.359915  0.762514  0.372276
2021-03-15  0.625464  0.863373  0.270713  0.940082

In [139]:
df.iloc[0:4, 0:2]

00.00     06.00
2021-03-09  0.877720  0.577552
2021-03-10  0.767632  0.206914
2021-03-11  0.150353  0.085990
2021-03-12  0.952085  0.309042

In [140]:
df.iloc[[0,2,4],[2,3]]

12.00     18.00
2021-03-09  0.758236  0.843486
2021-03-11  0.725898  0.077406
2021-03-13  0.220048  0.035815

In [141]:
df

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-13  0.027392  0.555903  0.220048  0.035815
2021-03-14  0.994721  0.359915  0.762514  0.372276
2021-03-15  0.625464  0.863373  0.270713  0.940082

In [142]:
df[df["12.00"] > 0.5]

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-14  0.994721  0.359915  0.762514  0.372276

In [143]:
df["12.00"] > 0.5

2021-03-09     True
2021-03-10    False
2021-03-11     True
2021-03-12    False
2021-03-13    False
2021-03-14     True
2021-03-15    False
Freq: D, Name: 12.00, dtype: bool

In [144]:
print(df2.iloc[0,0])

1.0


In [145]:
df2 = df.copy()

In [146]:
df2.iloc[0,0] = "HEHE"

In [147]:
df2

00.00     06.00     12.00     18.00
2021-03-09       HEHE  0.577552  0.758236  0.843486
2021-03-10   0.767632  0.206914  0.298570  0.098235
2021-03-11   0.150353  0.085990  0.725898  0.077406
2021-03-12   0.952085  0.309042  0.178235  0.937082
2021-03-13  0.0273924  0.555903  0.220048  0.035815
2021-03-14   0.994721  0.359915  0.762514  0.372276
2021-03-15   0.625464  0.863373  0.270713  0.940082

In [148]:
df

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-13  0.027392  0.555903  0.220048  0.035815
2021-03-14  0.994721  0.359915  0.762514  0.372276
2021-03-15  0.625464  0.863373  0.270713  0.940082

In [149]:
id(df)

3135401335536

In [150]:
id(df2)

3135401576768

In [151]:
df.loc["2021-03-13": "2021-03-14", "06.00": "12.00"]

06.00     12.00
2021-03-13  0.555903  0.220048
2021-03-14  0.359915  0.762514

In [152]:
df.loc["2021-03-13": "2021-03-14", "06.00": "12.00"] = np.nan

In [153]:
df

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-13  0.027392       NaN       NaN  0.035815
2021-03-14  0.994721       NaN       NaN  0.372276
2021-03-15  0.625464  0.863373  0.270713  0.940082

In [156]:
df.dropna(how="any")

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-15  0.625464  0.863373  0.270713  0.940082

In [157]:
df

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-13  0.027392       NaN       NaN  0.035815
2021-03-14  0.994721       NaN       NaN  0.372276
2021-03-15  0.625464  0.863373  0.270713  0.940082

In [158]:
df.dropna(how="any", axis=1)

00.00     18.00
2021-03-09  0.877720  0.843486
2021-03-10  0.767632  0.098235
2021-03-11  0.150353  0.077406
2021-03-12  0.952085  0.937082
2021-03-13  0.027392  0.035815
2021-03-14  0.994721  0.372276
2021-03-15  0.625464  0.940082

In [161]:
df.fillna(value=0.5, inplace=True)

In [162]:
df

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-13  0.027392  0.500000  0.500000  0.035815
2021-03-14  0.994721  0.500000  0.500000  0.372276
2021-03-15  0.625464  0.863373  0.270713  0.940082

In [163]:
df.isna()

00.00  06.00  12.00  18.00
2021-03-09  False  False  False  False
2021-03-10  False  False  False  False
2021-03-11  False  False  False  False
2021-03-12  False  False  False  False
2021-03-13  False  False  False  False
2021-03-14  False  False  False  False
2021-03-15  False  False  False  False

In [165]:
df.mean()

00.00    0.627909
06.00    0.434696
12.00    0.461664
18.00    0.472055
dtype: float64

In [168]:
df.mean(axis=1)

2021-03-09    0.764249
2021-03-10    0.342837
2021-03-11    0.259912
2021-03-12    0.594111
2021-03-13    0.265802
2021-03-14    0.591749
2021-03-15    0.674908
Freq: D, dtype: float64

In [169]:
df

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-13  0.027392  0.500000  0.500000  0.035815
2021-03-14  0.994721  0.500000  0.500000  0.372276
2021-03-15  0.625464  0.863373  0.270713  0.940082

In [171]:
df.apply(lambda x: x.max())

00.00    0.994721
06.00    0.863373
12.00    0.758236
18.00    0.940082
dtype: float64

In [172]:
df.apply(lambda x: x.max()+1)

00.00    1.994721
06.00    1.863373
12.00    1.758236
18.00    1.940082
dtype: float64

In [173]:
df.apply(lambda x: x.sum(),axis=1)

2021-03-09    3.056994
2021-03-10    1.371350
2021-03-11    1.039647
2021-03-12    2.376445
2021-03-13    1.063207
2021-03-14    2.366997
2021-03-15    2.699632
Freq: D, dtype: float64

In [174]:
df

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-13  0.027392  0.500000  0.500000  0.035815
2021-03-14  0.994721  0.500000  0.500000  0.372276
2021-03-15  0.625464  0.863373  0.270713  0.940082

In [175]:
# [1,2,3,4,5] => 1, 3, 6, 10, 15
df.apply(np.cumsum)

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  1.645351  0.784466  1.056806  0.941721
2021-03-11  1.795704  0.870456  1.782704  1.019127
2021-03-12  2.747789  1.179499  1.960939  1.956209
2021-03-13  2.775181  1.679499  2.460939  1.992024
2021-03-14  3.769902  2.179499  2.960939  2.364300
2021-03-15  4.395366  3.042872  3.231651  3.304382

In [176]:
df3 = pd.DataFrame([
                    [1,2,3],
                    [4,5,6]
])


In [177]:
df3

0  1  2
0  1  2  3
1  4  5  6

In [179]:
df3[:1]

0  1  2
0  1  2  3

In [180]:
pieces = [df3[:1], df3, df3[1:]]

In [181]:
pd.concat(pieces)

0  1  2
0  1  2  3
0  1  2  3
1  4  5  6
1  4  5  6

In [183]:
first = pd.DataFrame({"key": ["value1", "value2"], "left-val": [1,2]})
second = pd.DataFrame({"key": ["value1", "value2"], "right-val": [3,4]})
print(first)
print("#"*20)
print(second)

      key  left-val
0  value1         1
1  value2         2
####################
      key  right-val
0  value1          3
1  value2          4


In [187]:
pd.merge(first, second, on="key")

key  left-val  right-val
0  value1         1          3
1  value2         2          4

In [188]:
df

00.00     06.00     12.00     18.00
2021-03-09  0.877720  0.577552  0.758236  0.843486
2021-03-10  0.767632  0.206914  0.298570  0.098235
2021-03-11  0.150353  0.085990  0.725898  0.077406
2021-03-12  0.952085  0.309042  0.178235  0.937082
2021-03-13  0.027392  0.500000  0.500000  0.035815
2021-03-14  0.994721  0.500000  0.500000  0.372276
2021-03-15  0.625464  0.863373  0.270713  0.940082

In [189]:
df4 = pd.DataFrame(data)

In [190]:
df4

İsim    Boy  AyakkabıNumarası  Kilo
0   Ahnet  180.0              42.0    80
1    Ezgi  170.0               NaN    50
2  Mehmet  150.0              39.0    70
3   Sevda    NaN              36.0    45

In [208]:
data = {"isim": ["Ahmet", "Ezgi", "Mehmet", "Sevda", "Ezgi"],
       "boy": [180, 170, 150, 160, 150],
       "ayakkabiNumarası": [42, 37, 39, 36, 38],
       "kilo": [80, 50, 70, 50, 60]}

In [209]:
df4 = pd.DataFrame(data)

In [210]:
df4

isim  boy  ayakkabiNumarası  kilo
0   Ahmet  180                42    80
1    Ezgi  170                37    50
2  Mehmet  150                39    70
3   Sevda  160                36    50
4    Ezgi  150                38    60

In [214]:
df4.groupby("kilo").mean()

boy  ayakkabiNumarası
kilo                         
50    165.0              36.5
60    150.0              38.0
70    150.0              39.0
80    180.0              42.0

In [215]:
df4.groupby("isim").mean()

boy  ayakkabiNumarası  kilo
isim                                 
Ahmet   180.0              42.0  80.0
Ezgi    160.0              37.5  55.0
Mehmet  150.0              39.0  70.0
Sevda   160.0              36.0  50.0

In [216]:
df4.groupby(["boy","kilo"]).mean()

ayakkabiNumarası
boy kilo                  
150 60                  38
    70                  39
160 50                  36
170 50                  37
180 80                  42