In [1]:
import numpy as np

In [3]:
ND = np.zeros((4,3))

In [4]:
ND

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
ND = np.zeros((10,8))

In [8]:
ND

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
ND.ndim

2

In [10]:
ND = np.zeros(4)

In [11]:
ND

array([0., 0., 0., 0.])

In [12]:
ND = np.zeros((5))

In [13]:
ND

array([0., 0., 0., 0., 0.])

In [14]:
ND = np.ones((2,5))

In [15]:
ND

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
ND.dtype

dtype('float64')

In [18]:
ND = np.full((3,3),7)

In [19]:
ND

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [21]:
ND = np.eye(6)

In [22]:
ND

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [23]:
ND = np.diag([3,7,9,0,3,4,5])

In [24]:
ND

array([[3, 0, 0, 0, 0, 0, 0],
       [0, 7, 0, 0, 0, 0, 0],
       [0, 0, 9, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 5]])

In [28]:
ND = np.arange(20)  #[başlangıç, son]
ND

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
ND = np.arange(5,12)
ND

array([ 5,  6,  7,  8,  9, 10, 11])

In [30]:
ND = np.arange(6,18,5)

In [31]:
ND

array([ 6, 11, 16])

In [36]:
 ND = np.arange(20).reshape(4,5)

In [33]:
ND

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
ND=np.arange(20).reshape(2,10)

In [41]:
ND

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])