In [33]:
import numpy as np

In [34]:
ND = np.arange(20).reshape(4,5)
ND

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
ND[:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [36]:
ND[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
ND[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
ND[ :2, :2]

array([[0, 1],
       [5, 6]])

In [39]:
SlicingND = ND[1:4,2:5]

In [40]:
SlicingND

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [41]:
SlicingND[0,0] = 99
SlicingND

array([[99,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [42]:
ND

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 99,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [49]:
ND = np.arange(12).reshape(3,4)

In [50]:
ND

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
slicing2 = ND[:2, :2].copy()

In [53]:
slicing2

array([[0, 1],
       [4, 5]])

In [55]:
slicing2[0,0] = 99

In [56]:
slicing2

array([[99,  1],
       [ 4,  5]])

In [57]:
ND

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
ND = np.arange(12).reshape(3,4)

In [59]:
ND

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
ND = np.random.randint(0,10, (4,5))

In [64]:
ND

array([[3, 7, 3, 0, 1],
       [7, 9, 1, 1, 5],
       [9, 4, 9, 9, 8],
       [0, 6, 0, 9, 1]])

In [65]:
ND[ND[ : ] >= 5]

array([7, 7, 9, 5, 9, 9, 9, 8, 6, 9])

In [66]:
ND

array([[3, 7, 3, 0, 1],
       [7, 9, 1, 1, 5],
       [9, 4, 9, 9, 8],
       [0, 6, 0, 9, 1]])