In [1]:
import numpy as np

In [8]:
ND = np.random.randint(0,10,(4,4)) #Element - wise

In [9]:
ND

array([[5, 8, 7, 5],
       [1, 7, 8, 5],
       [4, 4, 4, 9],
       [5, 4, 6, 0]])

In [10]:
ND + 2

array([[ 7, 10,  9,  7],
       [ 3,  9, 10,  7],
       [ 6,  6,  6, 11],
       [ 7,  6,  8,  2]])

In [11]:
ND2 = np.random.randint(0,10,(4,4))

In [12]:
ND2

array([[1, 7, 0, 2],
       [0, 0, 5, 1],
       [3, 0, 5, 7],
       [4, 2, 3, 3]])

In [13]:
ND + ND2

array([[ 6, 15,  7,  7],
       [ 1,  7, 13,  6],
       [ 7,  4,  9, 16],
       [ 9,  6,  9,  3]])

In [15]:
ND3 = np.random.randint(0,10,(2,2))
ND4 = np.random.randint(0,10,(1,3))

In [16]:
ND3

array([[7, 5],
       [6, 7]])

In [17]:
ND4

array([[8, 1, 8]])

In [18]:
ND3 + ND4

ValueError: operands could not be broadcast together with shapes (2,2) (1,3) 